# Generated by Django 5.2.8 on 2025-11-21 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RootWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spelling", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                ("example", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spelling", models.CharField(max_length=255)),
                ("example", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "word_type",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("reflexive_verb", "Reflexive Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("pronoun", "Pronoun"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "root_word",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="words",
                        to="vocab.rootword",
                    ),
                ),
            ],
        ),
    ]
