# Generated by Django 5.2.8 on 2025-11-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootword",
            name="example",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="example",
            field=models.TextField(null=True),
        ),
    ]
