# Generated by Django 5.2.8 on 2025-11-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0002_alter_rootword_example_alter_word_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootword",
            name="example",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="example",
            field=models.TextField(blank=True, null=True),
        ),
    ]
