# Generated by Django 5.2.8 on 2025-11-22 17:36
from pathlib import Path
import yaml
from django.db import migrations


def load_seed_data(file_name):
    path = Path("vocab/seed_data")
    with open(path / file_name) as f:
        data = yaml.safe_load(f)
    return data


def seed_database(apps, schema_editor):
    Word = apps.get_model("vocab", "Word")
    Example = apps.get_model("vocab", "Example")

    seed_data = load_seed_data("initial_data.yaml")

    for word_type, words in seed_data["words"].items():
        for word in words:
            Word.objects.get_or_create(
                spelling=word["text"], definition=word["def"], word_type=word_type
            )

    for example in seed_data["examples"]:
        words = [Word.objects.get(spelling=word) for word in example["words"]]
        new_example = Example.objects.create(text=example["text"])
        new_example.words_used.set(words)


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0001_adds_models"),
    ]

    operations = [migrations.RunPython(seed_database)]
