# Generated by Django 5.2.8 on 2025-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0006_seeds_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="session_key",
            field=models.CharField(default="nosession", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="session_key",
            field=models.CharField(default="nosession", max_length=32),
            preserve_default=False,
        ),
    ]
