# Generated by Django 5.2.8 on 2026-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=255, unique=True)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_type', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('reflexive_verb', 'Reflexive Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('other', 'Other')], max_length=30)),
                ('session_key', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2500)),
                ('session_key', models.CharField(max_length=32)),
                ('words_used', models.ManyToManyField(related_name='examples', to='vocab.word')),
            ],
        ),
    ]
